// <auto-generated />
namespace FootballApp.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class EditTeamNotification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditTeamNotification));
        
        string IMigrationMetadata.Id
        {
            get { return "202012221104235_Edit-TeamNotification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
