// <auto-generated />
namespace FootballApp.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FriendRequests : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FriendRequests));
        
        string IMigrationMetadata.Id
        {
            get { return "202010190946216_FriendRequests"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
