// <auto-generated />
namespace FootballApp.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SupportTickets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SupportTickets));
        
        string IMigrationMetadata.Id
        {
            get { return "202101201112247_SupportTickets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
